### ISSUE TITLE
Engine crashes when loading 18b weights on latest 8Gen3 processor

### ISSUE THREAD

**Issue by abclike2000** [aki65/aki65.github.io#107]
Can it be compatible? I have tested every npu accelerator

![WechatIMG234](https://github.com/aki65/aki65.github.io/assets/149806795/64546681-d43b-4d4c-81ec-a5263ee8655d)

**Comment by aki65** [comment]
I re-built the app with the latest NPU interface libraries from Qualcomm (from Nov 1). According to the release notes these should support SD 8 gen 3. Due to lack of an 8 gen 3 device I can't test this, so please try it and report the result (new build is here: https://github.com/aki65/aki65.github.io/releases/tag/v1.19.2).

If it works, performance would be interesting, so please check the visits per second in the position from [test.sgf.txt](https://github.com/aki65/aki65.github.io/files/13257609/test.sgf.txt) and check if ticking "parallel evaluation" makes any difference.

**Comment by uestccokey** [comment]
The speed I tested on my 8Gen2 phone is 400v/s, and the speed on 8Gen3 phone is 460v/s.
There is no significant change in speed after parallel evaluation is turned on.

When running on these two mobile phones, both consume a lot of power and generate serious heat.

**Comment by abclike2000** [comment]
The speed I tested on my 8Gen2 phone is 400v/s, and the speed on 8Gen3 phone is 460v/s.
There is no significant change in speed after parallel evaluation is turned on.

When running on these two mobile phones, both consume a lot of power and generate serious heat.

**Comment by aki65** [comment]
Thank you very much for testing. If "parallel evaluation" yields no improvement, it's best to keep it off and use only 2 search threads. If you haven't done so already, please try that setting (on my test devices it showed significant improvement).

**Comment by aki65** [comment]
Concerning battery drain and device temperature the latest version might be interesting for you: https://github.com/aki65/aki65.github.io/releases/tag/v1.19.3

**Comment by abclike2000** [comment]
It works well, thank you!
