### ISSUE TITLE
Release 1.19.3  performance issues ?

### ISSUE THREAD

**Issue by bltoby** [aki65/aki65.github.io#108]
On my phone (8gen2 with 2 searchingthreads), 1.19.3 with 'npu mode set as 'burst' or 'sustained High-Performance' has a ca.20% performance drawback comparing with 1.19.2

Don't know if it's an individual case?

**Comment by aki65** [comment]
The only difference between 1.19.2 and 1.19.3 is that 1.19.3 uses the NPU mode from settings whereas 1.19.2 always uses "burst". So, if you set npu mode to burst in 1.19.3, the code executed is exactly same as in 1.19.2. Therefore a difference in performance can only be due to the considerable variance between performance measurements.
