### ISSUE TITLE
 能否加入“死活题棋谱”功能？

### ISSUE THREAD

**Issue by Jhering** [aki65/aki65.github.io#111]
就是在现有的load sgf界面、读sgf棋谱的基础上，
在载入死活题sgf文件时，能自动将ai的走棋局限于一角——就是死活题那一角，
而不是死活题只在一角、ai却在19路棋盘上别的地方下。
将ai的走棋局限于一角，
这样可以利用ai，很好地帮助初学者解决、学习死活题的解法。

**Comment by aki65** [comment]
As your last issue was in english, I'll answer in that language, since it is much easier for me than chinese.

You can limit AI analysis to a rectangle by tapping on the button with the dashed rectangle in the top row. A dialog will pop up, tick "Restrict analysis ...", then enter something like 20 in "Number of moves ..." to restrict the whole analysis sequence, then tap "ok" and define the rectangle on the board by dragging from one corner of the intended rectangle to the diagonally opposite corner.

If you have a life and death position, you can draw the rectangle around the position and usually solve it that way (unless ko is involved, because that area doesn't offer any ko threats). There is some more discussion on this in issue #6.

**Comment by Jhering** [comment]
All set. 

Thank you for your patience. 

"Restrict analysis ...", then enter something like 20 in "Number of moves ..."

What does setting above means?
I enter '1', and don't find any diffrence with entering '20'.
