### ISSUE TITLE
save sgf界面的设计逻辑有问题，外加一个bug

### ISSUE THREAD

**Issue by Jhering** [aki65/aki65.github.io#112]
1，save to same file和save to existing file，save to new file， 可以按通常做法，简化为 save 和 save as。
2，save to new file下面的filename，在填写名字的时候，却调用了安全键盘 secure keybroad，而没有调用正常的输入法，在中文环境里没法输入中文，同样，在德语环境里，也不能输入26个字母以外的字符。

**Comment by aki65** [comment]
As your last issue was in english, I'll answer in that language, since it is much easier for me than chinese.

1) Indeed, that's a little unusual, but there are reasons for this:
a) The user has to do different things in "Save to existing file" and "Save to new file" and I wanted to point that out clearly.
b) In a unified "Save as" the user would have to enter the file name (if needed) in the android system file picker (which I can't change) and that one allows entering any file name. So the user can choose a different suffix than .sgf (or none at all), which would result in a file, that he can't open in the app afterwards. To prevent that, I force entering the file name in the app (so that I can add the .sgf suffix if neceessary), but that leads to the current dialog structure.

2) It's not intended, that the file name editing field opens the secure keyboard, and it doesn't do so on my phones. It opens the standard keyboard and I can enter any characters. If that is different on your device, it's probably due to system settings. But maybe there is a workaround. After having tapped "Choose directory", you can still edit the filename (at the bottom of the display). Perhaps you can enter more characters there.

**Comment by Jhering** [comment]
In 'save to new file', when i don't input any charactor in the field, the button 'choose directory' is invild. 
On my device, it call the security keybroad, after your advice, i can edit the 'name.sgf' in the opened window by using 'choose the directory'.
And the problem is, it turns out 3 steps when i deal with it.

1. type anything, to make the 'choose directory' button valid.
2. click the button.
3. edit the name.sgf using any charactor.

Could you make the 'choose directory' button valid before i type anything in the blank field? And then the steps trun to 2 instand of 3. 

Thank you.

**Comment by aki65** [comment]
I changed this in the latest release: https://github.com/aki65/aki65.github.io/releases/tag/v1.19.5
