### ISSUE TITLE
Could there be a colered circle?

### ISSUE THREAD

**Issue by Jhering** [aki65/aki65.github.io#115]
![IMG_20231206_212715.jpg](https://github.com/aki65/aki65.github.io/assets/1128376/e79f653e-58f3-4a3e-bf10-89ecd36b54d2)

When I use the B/W mode, the analyse scores on the white game board and bottom bar lose colored circles, and it looks wired.

Could it will be improved?

**Comment by aki65** [comment]
It's intended that the analysis circles are not colored as usual, since the b/w mode is designed for use on e-book readers. On their b/w display a black writing on a red circle (for example) would appear as black on dark grey and therefore be difficult to read.

But it was a bad choice to make them white, since they can't be well distinguished from the white board. So I will make them light gray.

**Comment by aki65** [comment]
This is now included in the latest release: https://github.com/aki65/aki65.github.io/releases/tag/v1.19.7
