### ISSUE TITLE
It seems that the winning rate of lz engine is always between 12% and 88%.

### ISSUE THREAD

**Issue by uestccokey** [aki65/aki65.github.io#12]
I tested a lot of sgf, it seems that the winning rate of lz engine is always between 12% and 88%.
![PNG图像](https://user-images.githubusercontent.com/7234924/103980246-7bef9d80-51ba-11eb-89bc-59ee06ec1535.png)

The kata engine is no problem.
![PNG图像 2](https://user-images.githubusercontent.com/7234924/103980218-6d08eb00-51ba-11eb-861a-c40ba5816218.png)

**Comment by cryptsport** [comment]
@uestccokey
1 sabaki & leela show the same winrate
2 there are games with different winrate

**Comment by aki65** [comment]
The optimization of the LZ networks for android leads to slightly different outputs. For the winrate the difference is very low in positions between 20% and 80% (mostly below 1%). Beyond 20% and 80% it gets a little bigger (2-3%) until the winrates of the optimized networks are "capped" at 12% and 88%.
All this doesn't affect playing strength (I ran a series of test matches between the original network and the optimized one at equal playouts and the result was even), which is plausible, since game is won or lost anyway between AI programs beyond 12% or 88%, so  a deviation in this area doesn't really matter.
Therefore I consider this a low price to pay for the speed increase, you just have to interpret "12%" as "<= 12%" and "88% "as ">= 88%".

**Comment by uestccokey** [comment]
Thank you for your reply

**Comment by aki65** [comment]
This winrate "cap" is now eliminated with the new optimization method in version 1.9.0.
