### ISSUE TITLE
A special version without integrated network.

### ISSUE THREAD

**Issue by bltoby** [aki65/aki65.github.io#130]
It's very interesting to have KataGo's human SL network supported.

Can you please make a special version without any integrated network, only use the human SL network for training plays. 
 
Further more, when 'play black' or 'play white' is set, it can't be modified during the game and both can't be enabled at the same time.

So that badukai can be transferred as a pure training software without any analysis function, this could be helpful for many people.

Thanks.

**Comment by aki65** [comment]
I don't see how reducing the functionality of the app would be helpful. Anyone who doesn't need a certain feature (for example analysis) can simply not use it.

**Comment by bltoby** [comment]
Emm... no kids( not a single one, as far as I know) can refrain from peeking tips, if they have a chance to do that. After all the game is hard to learn. That's why I have got the idea to ask for a function reduced version.

**Comment by aki65** [comment]
I made a reduced version here: https://github.com/aki65/aki65.github.io/releases/tag/v1.20.2

It already includes the human SL network (but not the others), so no need to load it from storage, you can start playing immediately.

**Comment by bltoby** [comment]
Thank you very much for the special version. In my opinion, it's almost perfect. 

Since 'undo move' button is essential for real case of fat finger, but can also be a temptation for wrong purposes. If a counter for undone moves be added like the attached picture and save the info in sgf file just like captures, this training tool will be indeed 100% perfect for people (not only kids) who take learning weiqi/go/baduk seriously, even though only at amateur level.

**Comment by aki65** [comment]
If you want to log the "undos" in the sgf, I would suggest a much simpler solution:

I could disable the "undo" button. Then, moves could still be corrected by the arrow keys (go back and make another move), so "fat fingers" are protected. But each such action would create a variation in the sgf, and so could easily be tracked afterwards. As a bonus, you would see both the original and the corrected move in the sgf, which might give an indication if it was a misclick or correction of a move that turned out badly.

**Comment by bltoby** [comment]
sounds very good, a pretty smart solution.

**Comment by aki65** [comment]
I released that modification: https://github.com/aki65/aki65.github.io/releases/tag/v1.20.3
