### ISSUE TITLE
Could not input Chinese while save to new file [Filename]

### ISSUE THREAD

**Issue by ivysrono** [aki65/aki65.github.io#131]
1.20.1

1. 'save sgf'

2. Type Chinese in 'Filename:'

3. Get mojibake (nonsense characters displayed when software fails render text according to its intended character encoding)

**Comment by aki65** [comment]
If the language of the device is chinese or korean or japanese (so that the app runs in that language), then asian characters are displayed correctly in "Filename:", at least in my tests.

If the language of the device is something other than chinese, korean or japanese (so that the app runs in english), then a different font is used, that indeed can't display asian characters (which should not be a problem, since they are not expected when the app is run in english).

**Comment by aki65** [comment]
I made a new version ( https://github.com/aki65/aki65.github.io/releases/tag/v1.20.4 ). You can now switch the app's language to chinese without changing the system language.
