### ISSUE TITLE
It seems that the optimized 20b Kata weight is not supported more than komi 10

### ISSUE THREAD

**Issue by uestccokey** [aki65/aki65.github.io#14]
It seems that the optimized 20b Kata weight is not supported more than komi 10?
When I set the komi to 20, I get the same winning rate as when I set the komi to 10. 

But the ordinary 20b weight does not have this problem.

**Comment by aki65** [comment]
That's true, results of the optimized network are only accurate for komi between -7.5 and 7.5. Komi above 7.5 will yield almost the same result as 7.5, komi below -7.5 will yield almost the same result as -7.5. So there is practically no difference between 10 and 20.

This stems from the quantization which is used to speed up network evaluation. Here one can choose between
a) handling a big (symmetrical) komi range with a uniform medium network evaluation error
or
b) handling a small (symmetrical) komi range with a small evaluation error at the price of getting big errors for komi outside this range

I opted for b) because it yields much more accurate network results for the wide majority of use cases (after all you are the first one to even notice this).

**Comment by uestccokey** [comment]
Ha ha. Thank you
