### ISSUE TITLE
[Multiple Features Suggestion]: SGF-PDF-Image, Real Wood Board, Analyze by po or v...

### ISSUE THREAD

**Issue by HackYardo** [aki65/aki65.github.io#20]
I don't know what is the final goal of BadukAI, I also don't know how many programming skills do you have, but these features are useful and convenient:

- **read different file directly**, for examples .txt .zgf(ZenithGo) .gib(www.eweiqi.com)
- **convert sgf into** pdf, static image, gif, for examples:
![image](https://user-images.githubusercontent.com/57677458/107851352-4aff2a00-6e44-11eb-9ad4-4a4ae3c7e0ab.png)
![gif](https://user-images.githubusercontent.com/57677458/107851435-ce208000-6e44-11eb-8804-791780cea8d8.gif)

- **create sgf from camera or photo**, for example, generate sgf from the "leesedol vs alphago game 4" static image above, recognizing the move numbers on the stones as the order of the stones
- **Real Wood Board Theme**, from Sabaki: 
![board](https://user-images.githubusercontent.com/57677458/107852381-5c980000-6e4b-11eb-9853-790a366049b2.png)

- **visualization of ownership predictions**, for examples,  
![katago20selfplay](https://user-images.githubusercontent.com/57677458/107852758-75a1b080-6e4d-11eb-8b52-f2103b55877f.png)
<img width="516" alt="territory" src="https://user-images.githubusercontent.com/57677458/107852865-01b3d800-6e4e-11eb-8007-ee5842fca998.png">
(from https://arxiv.org/abs/1902.10565/)

- **analyse all based on playouts or visits**,  now "analyse all" may skip some moves without giving a histogram if the sec/move is too small or the board position is too complicated. 

- **accelerate "analyse all" if several continuous board positions are on the same known tree**, I don't know if it make sense.  Another: If "analyse all" from end to begin, could it pick up speed? Because the whole game tree are known.

- **clock mode**,  for examples, 5min+10sec*5, 30min+0*0, 0+30sec*3

- **add local page "How to Use" (the same to https://aki65.github.io/) to app**

**Comment by aki65** [comment]
Sorry for responding so late, but it took some time to analyze all this.

**read different file directly**
Which kind of data should be read from these files ? Game records ?

**convert sgf into pdf, static image, gif**
I don't see any need to have this on a phone. And on PC there are already several sgf editors who can do this (e.g. cgoban3). So no need to reinvent the wheel here.

**create sgf from camera or photo**
That's interesting, though not in the scope of BadukAI. I created another app ImgToSgf some months ago, which does the basic part of this: converting an image into a static sgf (with set stones). It doesn't read any numbers yet. But if I find the time, I will try to add this feature.

**Real Wood Board Theme**
BadukAI already uses a wooden board texture. It is just not as pronounced as your example. On a phone, the stones and all the other symbols on the board are quite small, so care must be taken that the board texture doesn't affect their visibility.

**visualization of ownership predictions**
I added this in version 1.6.

**analyse all based on playouts or visits**
**accelerate "analyse all" if several continuous board positions are on the same known tree**
In version 1.6 I added the option to control analysis by number of visits. This addresses both points, as visits from previous positions will be re-used.

**clock mode**
I consider this second priority, as it seems a rare use case.

**add local page "How to Use" (the same to https://aki65.github.io/) to app**
A good idea, but also second priority to me, since it's not much different from viewing the web page in a browser in parallel.

**Comment by HackYardo** [comment]
**read different file directly**
not use for some data, just for convenience, if download a .gib kifu from app or website to a phone, Android can't open it. however, it is much more convenient if use a computer😂
**convert sgf into pdf, static image, gif**
just for convenience too, if one wants to share a game from BadukAI, he or she can use screenshot, but it contains less information than a image or gif created by a computer.
**create sgf from camera or photo**
it is a big feature if recognize the move numbers, good luck!
**Real Wood Board Theme**
sorry for this suggestion, I open eyes-friendly mode on my phone, so I just see an orange board instead of a wood board🙄
**visualization of ownership predictions**
how does BadukAI predict ownership? by KataGo engine or another method? I suggest this feature because many old Go software can judge fairly complex tsumegoes (not all tsumegoes) on a board position while young Go software (after AlphaGo 2016) only can judge very easy tsumegoes or don't judge tsumegoes at all. I don't know why.

**Comment by aki65** [comment]
> how does BadukAI predict ownership? by KataGo engine or another method?

By KataGo's ownership prediction. I checked only a few positions, but these were accurate (concerning life and death)

**Comment by HackYardo** [comment]
Do you combine the KataGo ownership predict analyze command and the graphic part of Sabaki estimate feature? I plan to write(mostly fork then modify) a computer Go GUI or CLI, its goal is needing smallest watt, I think it should show ownership prediction like BadukAI does.

**Comment by aki65** [comment]
I don't know how Sabaki does it. I simply draw an overlay over the board which is colored according to KataGo's ownership prediction (which I gain from command "kata-anlayze ... ownership true"). The color around an intersection with predicted ownership p is (r,g,b,a) where (with white to move):
a = 0.6 (transparency)
r = g = b =
1 if p > 0.5
0 if p < -0.5
p + 0.5 otherwise

**Comment by HackYardo** [comment]
My programming level is using languages as calculaters, I can understand your pseudocode easily, but I don't know how to draw an overlay over the board, I will study it by searching keywords(e.g. "estimate") in sabaki or some repo similar. 

Good luck to your ImgToSgf. Reading numbers in converting img into sgf is a big feature.

This issue completes its mission, I close it.
