### ISSUE TITLE
loading network by default in version 1.5.1

### ISSUE THREAD

**Issue by cryptsport** [aki65/aki65.github.io#21]
it would be convenient: if default_model.bin.gz is in the folder with the apk file, then when you start BadukAI it is loaded. probably better at start launching KataGo

**Comment by aki65** [comment]
The reduced APK is completely identical with the full APK except that all network files are removed. Everything else would be too awkward to handle. Therefore the default settings must also be identical. And the full APK is also for casual users. So I don't like to include such hidden conventions as you suggest with default_model.bin.gz. But  starting with katago surely makes sense for the wide majority of users, so I will include that in the next release.

**Comment by cryptsport** [comment]
I may not have expressed my point accurately enough. I propose not a change, but an addition. you can do the same on the regular version. now, when the BadukAI starts, the network is loaded, which may not be needed (v 1.5) or a crash message (v 1.5.1). I suggest: the application works as usual, but if the user wants, he will add a default_model.bin.gz network and it will load on startup. it is convenient and fast. someone usually uses the same network, the application is updated frequently, imagine how it works, it's very convenient. who does not want to - can not use it. but the additional feature is good!

**Comment by cryptsport** [comment]
there is another solution. is it possible to save settings when updating the program? if you install a new version without removing the old one? Anyway, thanks again for the great app!

**Comment by aki65** [comment]
Ok, I understand. So in the next version I will add that default_model.bin.gz from the root directory of the internal storage will be loaded If the configured model is not found. This will not change anything for the full APK, but load this model out of the box with the reduced APK.

**Comment by cryptsport** [comment]
I'm very grateful to you!

**Comment by aki65** [comment]
This is now implemented in version 1.6. Keep in mind:
a) You must install the reduced APK of version 1.6 as an update over a previous version (otherwise the app won't have storage permission right from the start and won't be able to access default_model.bin.gz)
b) The optimized networks can only be used for the 19x19 board. Normally the UI will block using them on other board sizes, but when using the "fallback" default_model.bin.gz, the UI doesn't know which kind of network it is. So please make sure yourself, that you load an original Katago network before switching to a board size other than 19x19.

**Comment by cryptsport** [comment]
Thank you so much!!!
