### ISSUE TITLE
Add Move-Score Histogram

### ISSUE THREAD

**Issue by HackYardo** [aki65/aki65.github.io#24]
The move-winrate histogram may become readless and meaningless when winrate changes in a slit of 90%-100% as the scorediff is over 8. And a game of 300 moves will come to an end at move-30 because the winrate is around 95% from move-31 to move-300. So could you add move-score histogram?

**Comment by aki65** [comment]
The big question with a move-score histogram is how to scale it, as there is no fixed range such as 0-100% with the winrate. But I will think about it.

**Comment by HackYardo** [comment]
I see some apps on desktop, they have a changeable scale, for examples, the scale is 10 when max scorediff is 8, the scale is 150 when max scorediff is 128. But I don't know if there has spare space for it. If use a big fixed scale like 256 or 361, the move-score histogram maybe hard to read if the max scorediff of a game is only 5.

**Comment by HackYardo** [comment]
The delta-score histogram and the delta-winrate distogram are creative and funny! I find the maxKomi is different from original KataGo.  Do you define komi  [-10, 10] ?

**Comment by aki65** [comment]
I did not change anything regarding komi, so with original KataGo networks it should behave as original KataGo.
However, the optimized networks only work well with komi between -7.5 and 7.5 
(see this issue [https://github.com/aki65/aki65.github.io/issues/14](url))

**Comment by HackYardo** [comment]
I try several different komi value and then analyze at move 0 :

komi lead-score(10b 20b)
200 -0.5 -1
150 -74.5 -3
100 -55 -3
50 -33 -3
20 -13 -3
10 -3 -2
7 0 0
6 0.5 0.5
0 6 7
(maxKomi is 150 in original KataGo)

 It seems that something wrong. The relation between Δkomi and Δleadscore is confused.

I see issue#14, the reason about 20b is it is a optimized network. But isn't 10b a original network?

**Comment by aki65** [comment]
Yes, 10b is original network. But did you also check the lead values with this network and the original KataGo binary ? I would expect them to be the same ...

**Comment by HackYardo** [comment]
![image](https://user-images.githubusercontent.com/57677458/110802822-85c87680-82b9-11eb-8885-fc72df564549.png)
I mean if on a computer, the relation between Δkomi and Δleadscore is clear.

**Comment by aki65** [comment]
Thanks for the log. It seems that the reason for the difference is as follows:

KG's analysis includes two "score-related" values (quoted from the documentation):

**scoreLead** - The predicted average number of points that the current side is leading by (with this many points fewer, it would be an even game).
**scoreSelfplay** - The predicted average value of the final score of the game after this move from low-playout noisy selfplay, in points. (NOTE: users should usually prefer scoreLead, since scoreSelfplay may be biased by the fact that KataGo isn't perfectly score-maximizing).

final_score seems to rely on scoreSelfplay. But BadukAI uses scoreLead (following the recommendation from the docs) and this is much lower (at least for the 10b network).

**Comment by HackYardo** [comment]
Thanks a lot. The last time I read it(KG doc), I mainly looked at the rule set. And now, I need to read it from begin to end again.
