### ISSUE TITLE
ADD CHINESE TRANSLATION

### ISSUE THREAD

**Issue by HackYardo** [aki65/aki65.github.io#25]
Because BadukAI has not many items, I could translate into Chinese in a day.

**Comment by aki65** [comment]
Thank you very much for this offer which I happily accept.

I attached the translations file, which includes one block for each english text. I added a chinese translation (language code: 'zh') from google in the first block as an example of the required format.

The translations are given in unicode notation. To convert chinese glyphs into unicode you can use this website [https://www.branah.com/unicode-converter](url). 

Some texts have to be broken into multiple lines because they are too long for the available space. This is indicated by line-breaks \n. This will be necessary for some chinese translations, too. You can get an indication of how much fits into one line by looking at the positions of the \n in the english, korean and japanese texts.

[translations.txt](https://github.com/aki65/aki65.github.io/files/6085971/translations.txt)

**Comment by HackYardo** [comment]
[translationsAddZH.txt](https://github.com/aki65/aki65.github.io/files/6091536/translationsAddZH.txt)
BeCareful : the file name changed

**Comment by HackYardo** [comment]
Sorry for an error, in 'visits/move in analysis', the 2nd char is not 65f6, it should be 6790

**Comment by HackYardo** [comment]
This translation needs considering WeiQi/Go/Baduk, GTP, English&Chinese, AI(especially MCTS), KataGo, basic programming, and final user-friendly expression.

Some words and how they be translated:
move(n) : "手" "着" 
move(v) : "行棋" "落子"
play(v) : "对弈" 
play(n) : "弈"
position : "盘面" "位置"
ponder : "分析", the same to 'analyze'
evaluate : "计算", the same to 'compute' or 'calculate', just for simplification
playout : "模拟对局" "新增模拟对局"
visit : "总模拟对局", the difference between playout and visit is: Playouts and visits are both counting the same thing (one more leaf node in the tree of explored variations) but playouts are a delta per move, whilst visits are the total across tree reuse from previous moves. 

From: 
https://lifein19x19.com/viewtopic.php?f=18&t=17195&start=100

https://github.com/lightvector/KataGo/blob/master/docs/Analysis_Engine.md

http://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html#SECTION000311000000000000000

https://senseis.xmp.net/

https://benlauwens.github.io/ThinkJulia.jl/latest/book.html

**Comment by aki65** [comment]
Thank you very much for putting so much thought into the translations. I will include them in the next release.

**Comment by HackYardo** [comment]
I debug the translation file again, hope my work doesn't clash your work. Its version is the final version before next BadukAI release.
[translationsAddZHver2.txt](https://github.com/aki65/aki65.github.io/files/6096509/translationsAddZH2.txt)

**Comment by HackYardo** [comment]
I translate the index.html too, here it is:
[indexZH.html.txt](https://github.com/aki65/aki65.github.io/files/6096639/indexZH.html.txt)

**Comment by HackYardo** [comment]
By the way, what does 'n/s' mean? 'nodes per seconds'? Is it the same to po/s or v/s? Or something else?

**Comment by HackYardo** [comment]
By the way, what does 'n/s' mean? 'nodes per seconds'? Is it the same to po/s or v/s? Or something else?

**Comment by aki65** [comment]
Thank you very much for translating index.html, too, that's really helpful.

"n/s" indeed means "nodes per second". I see this often when speed is measured. I never found an exact definition, but I assume it's the same as v/s or po/s.

**Comment by HackYardo** [comment]
- Some new items of 1.8.0 can't display integrally on the little size screen of my phone... 
![distortion](https://user-images.githubusercontent.com/57677458/110332738-b0b58f00-805b-11eb-81ad-ced2c820668f.png)

Because it seems that 'winrate' and 'histogram' are on the same level, I suggest you change the places:

histogram: ▢ △-score, upto ± ▭
▢ winrate  ▢ △-winrate, upto ± ▭
    | |
    | |
   \\/
Histogram:
\t ▢ winrate  
\t ▢ △-winrate, upto ± ▭
\t ▢ △-score, upto ± ▭

And you can put some other buttons in 'Edit config'.

- What is the meaning of the parameter 'numMovesToRandomize' in LeelaZero? 
I can't find it out by Bing or Github search engine...

- Why LeelaZero's analyzing (via 'ponder' & 'analyse all') is capped by 'maxPlayout' & 'maxVisit' while KataGo is not?
![maxpo&v=1](https://user-images.githubusercontent.com/57677458/110332840-d773c580-805b-11eb-99aa-3b25dd9fd67c.png)
I set maxPo = 1 and maxV = 1, KataGo's analyzing not changes only when 'v/m in analysis' change. 

- How about saving sgf with automatically adding .sgf suffix?

- Can't read sgf files created by other Go APPs, I don't know why. For example:
(;FF[4]CA[gb2321]SZ[19]id[2020-12-02]AP[wqbd]GN[#2020]DT[2020]PC[]AN[]KM[7]HA[0]PB[L]PW[T]BR[]WR[]RE[]N[@围棋宝典 ]C[#2020 黑 L VS 白 T ];B[pd];W[pp];B[dd];W[dp];B[cn];W[fq];B[qq];W[pq];B[qp];B[bd];W[lo];B[ee];W[ff];B[em];W[mr])

- At last, Could you add 'translations.txt' to BadukAI repo? So that I could follow the last version of BadukAI, update chinese translation and avoid clashes between us. Moreover, I find tow translation errors in index_zh.html, and this html needs adding string "English Version" in the top-right corner!

**Comment by aki65** [comment]
> Some new items of 1.8.0 can't display integrally on the little size screen of my phone...

Your suggestion certainly looks much nicer, but it takes four lines instead of two. And the settings menu is already as long as the screen on phones with 16:9 aspect ratio (I checked with my old one). That's why I squeezed it into two lines (and as all go players know, squeezing can make bad shape). Joking aside, I can make the settings menu a little wider (even on your screenshot there is still space to the left), then the text should fit.

> What is the meaning of the parameter 'numMovesToRandomize' in LeelaZero?

It controls the parameter -m (meaning: "Play more randomly the first x moves"). That one doesn't have a telling short name, so I had to invent one (that's why you can't find it on search engines)

> Why LeelaZero's analyzing (via 'ponder' & 'analyse all') is capped by 'maxPlayout' & 'maxVisit' while KataGo is not?

KG and LZ behave differently here. BadukAI puts "maxVisits" and "maxPlayouts" in the config in both cases. For LZ this restricts both play and analysis. For KG this restricts only play.

> How about saving sgf with automatically adding .sgf suffix?

Good idea.

> Can't read sgf files created by other Go APPs, I don't know why. For example: ...

There are two problems in the sgf file:
1) the "id" property: The parser doesn't like it (and I could not find it in the sgf specification, maybe some kind of extension ?)
2) the "CA" property: The parser does not know the encoding "gb2321" (probably it is limited to western text encodings)

If I delete the parts "CA[gb2321]" and "id[2020-12-02]" with a text editor, BadukAI loads the file correctly.

> At last, Could you add 'translations.txt' to BadukAI repo? ...

I will do so. 
As far as index_zh.html is concerned, it is also missing the new part where I explain the display of differences in the histogram (since I added this after you translated).

**Comment by HackYardo** [comment]
[index_zh.html.txt](https://github.com/aki65/aki65.github.io/files/6109801/index_zh.html.txt)
I update the index_zh.html from 1.7.0 to 1.8.0, you can just use it instead of the old one.

**Comment by aki65** [comment]
I uploaded the new index_zh.html

**Comment by HackYardo** [comment]
- I find a big error in index_zh.html, the two screenshots of BadukAI should be zh rather than en! 

- Can I add zh extension after the end of index_zh.html to introduce something out of index.html? For example, kata1-...-680... in release 1.8.1.

- Can BadukAI ignore "id" and "CA" for reading sgf file created by some other Go APPs?

- If the buttons of settings are wider and wider, which are enough to contain explanation, shall we add them? For example:

kyu-rank
| |
| |
\\/
kyu-rank(30=30K, -8=9D)

**Comment by HackYardo** [comment]
If you are not worried, I make index_zh.html **line to line** index.html. It maybe helpful in compare they two. And it will be used as a supplementary of git diff.
[index_zh.html.line2line.txt](https://github.com/aki65/aki65.github.io/files/6124345/index_zh_line2line.html.txt)

 BTW, how about use LZ 287(the last one) rather than LZ 286?

**Comment by aki65** [comment]
I checked in the new index_zh.html.

As for LZ 287, I might do it some day, but I don't consider this urgent, as the Elo difference to LZ 286 is very small.

**Comment by HackYardo** [comment]
Thanks. The next index_zh.html to follow index.html, I will request a pull to BadukAI repo.
