### ISSUE TITLE
[BUG] 'winrate on play' takes effect in analyzing

### ISSUE THREAD

**Issue by HackYardo** [aki65/aki65.github.io#26]
Turn off 'winrate on play' then turn on 'analysis all', the 'winrate for W' and 'score-lead for W' will disappear.

**Comment by aki65** [comment]
If you turn on "analyse all", the row with 'winrate for W' and 'score-lead for W' will be replaced by the row with the best moves. This always happens independent of the setting "winrate on play". When you see the moves, you don't need a display of winrate and score-lead, since both are already displayed within the moves.

**Comment by HackYardo** [comment]
After analyzing all positions, if go back to previous positions, the row with the best moves will be replaced by the row with 'winrate for W' and 'score-lead for W'. But if turn off 'winrate on play', the row with the best moves will be replaced by none.

**Comment by aki65** [comment]
Ah, that's what you mean.

Here, indeed, the setting "winrate on play" takes effect, because BadukAI has finished analysing (it has done all positions), so it is in play mode again. 

But no need to worry about this, it will soon change anyway: When the analysis results become persistent (for writing and reading them), then BadukAI will probably show the moves found during analysis, when you navigate to a position which was previously analyzed.

**Comment by HackYardo** [comment]
In your words, I see two modes. I used to think there are all three modes:
play mode: if turn on 'play B' or 'play W'
analyze mode: if turn on 'analysis all' or 'ponder'
edit mode: all other cases
However, it is not important because the analyzed results will be persistent.
