### ISSUE TITLE
provide optimized  human-style weights

### ISSUE THREAD

**Issue by WindOfStorm** [aki65/aki65.github.io#30]
could you please add  optimized  human-style weights? for example，leelamaster GX78,leelamasterGXA4,leelamasterE08,anyone is ok.I could provide you with  them,if you need.you can  get them  here (https://github.com/pangafu/LeelaMasterWeight)also.looking forward to  your reply.

**Comment by aki65** [comment]
I can do so, but there are a few prerequisites:
1) I must resolve the performance problems on snapdragon 888, since this may require changes in the network structure (see issue #29)
2) I must provide a mechanism to sideload LZ networks, since the APK has already reached the maximum size allowed in play store, so I can't include more built-in networks.

Only then I can start to optimize other weights, so it may take some time.

**Comment by WindOfStorm** [comment]
Thank you for your hard work.Hope you make it.

**Comment by aki65** [comment]
This is now included in release 1.9.0

**Comment by WindOfStorm** [comment]
Thank you  very very very   much
