### ISSUE TITLE
kyu bots weaker in 0.16.0 than 0.14.0?

### ISSUE THREAD

**Issue by portkata** [aki65/aki65.github.io#4]
It might be just me, but I feel like the kyu bots are weaker in version 0.16.0 than 0.14.0. I use the kyu rank 10 bot with the 6b net. In 16, if you attack a group in the beginning, eventually the bot will give up defending and you can always capture it. In 14, you can never just capture a group that can easily escape, unless the bot is strategically sacrificing the group for territory elsewhere. it will trap you instead. Thanks!

**Comment by aki65** [comment]
I did not change anything in the algorithm of the kyu-rank bots, I only excluded the multi-suicide moves from the list of moves to consider (and this should not matter in the beginning). And's first results also suggest that their strength has not changed. So I assume that your observation is caused by the random nature of the play of the kyu-rank bot (especially at lower strength levels).
