### ISSUE TITLE
Where is the file folder after installation?

### ISSUE THREAD

**Issue by HackYardo** [aki65/aki65.github.io#5]
I run BadukAI on my Android phone, but it is weaker than KaTrain or Sabaki with KataGo on my laptop when config the same number of visits. So I want to find the default_gtp.cfg on my phone to see what is the cause. But I can't find it.

**Comment by aki65** [comment]
It's in the app's installation directory under /data/data, but you can't read this due to android's security restrictions (unless phone is rooted). Therefore I attached the static part of the configuration. Add the values you enter in the configuration dialog, and you get the configuration file at runtime.
Another point to mention in this context: KataGo stops calculation if either maxVisits or maxPlayouts or the maximum time per move is reached ("sec/move" from settings). So if you want to ensure a certain number of visits, enter a very large value for "sec/move", so that this never becomes a constraint.
[gtp_static.txt](https://github.com/aki65/aki65.github.io/files/5542598/gtp_static.txt)

**Comment by HackYardo** [comment]
@aki65 
You are right, my phone needs much more time than laptop in running all 500 visits. Maybe 90 seconds? My laptop needs only 6 seconds.
