### ISSUE TITLE
Problem with kyu-rank parameter

### ISSUE THREAD

**Issue by illydone** [aki65/aki65.github.io#56]
Hello

I used the 1.13 version.

I'm a starter player and as such, I wanted the AI to be at a low level.

I first tried a 19x19 grid, at 30 kyu-rank with the 20b network. AI is black but even for me, il seems to choose its moves randomly. I can try to surround its stones and it never stops me. I can put it in atari and it never protects its stones, etc. etc. After we reach what seems to be the end of the game, AI still fills the grid, it never passes nor resigns.

30k is low and my game is poor. I tried to let it play against itself 19x19, 30k and 20b network, and the result is the same: it fills the grid and captures stones indefinitely and never passes or resigns. Same if I try with 1 (1k) or -8 (9d) kyu-rank.

I tried several configurations of the AI playing againt itself, also with 9x9 grids, but as soon as I put a kyu-rank, the bot doesn't "work" any more.

I finally tried a 9x9 grid against itself, with no kyu-rank and in this case, it plays correctly and black or white wins after the two passed.

Am I missing something?

**Comment by aki65** [comment]
Let's address these issues one by one:

1) The 30k kyu-rank bot plays "random" moves
The "kyu-rank" mechanism basically makes a very strong bot (the 20b network) much weaker by restricting its choice of moves to a random subset of all possible moves. The smaller the subset, the weaker the resulting move (on average). The advantage of this method is its simplicity: By varying the size of the subset, you can achieve any desired strength. The downside is: To reach low ranks (like 30 kyu), the subset must be so small, that it sometimes contains only absurd moves. That's what you observe.

2) The 30k kyu-rank bot is too weak
The parameters for the subset size were calibrated by playing on an online go server against humans (not by myself, but by another project). But I assume that there were very few matches against 20+ kyus, so the parameter values for this range may be a little off. Moreover, you perhaps expect too much from a 30k: A 30k just knows the rules, he (or she) usually doesn't think about being enclosed.

3) The kyu-rank bot doesn't pass or resign
That's true. Because of its algorithm (see above) he doesn't know or estimate the state of the game, so he has no clue when to pass or resign.

So these three issues are not programming errors, but rather a consequence of the method, more like "the ugly side of the coin".

For your purposes I suggest the following:
Do not use the 20b network, but load a weaker one (e.g. https://media.katagotraining.org/uploaded/networks/zips/kata1/kata1-b6c96-s56669696-d8173106.zip ). The way to load an external network is described at https://aki65.github.io/#settings. Then you can set a better kyu-rank (like 15k) without the bot getting too strong. This will reduce the "randomization" effects. Additionally, you can tick "opening book" in the settings to get a more human-like opening.
When you feel that the game is pretty much finished, turn off the kyu-rank. Then the KataGo network will take over, and it will pass/resign when appropriate (and its additional strength won't matter since everything has been settled anyway).

**Comment by illydone** [comment]
Thanks for the answer. Let's forget the 30k rank, it was just a try.

I have the same behaviour by setting it to 1k, 3d or 9d: the bot plays indefinitely against itself. Moreover, the play speed seems exactly the same as when set 30k. I only get a difference when removing the kyu-rank: it is far slower and seems to have different gameplay, even when adding time settings. However, I must admit that my poor level doesn't help and except the play speed and the fact it never passes/resigns, I can't really analyse what it is doing.

Thanks for the suggestion at the end of the play. I already tried that and it seems ok for me... except it often resigns so no help on counting and finding when a game should end, but that's another story. ;)

**Comment by aki65** [comment]
_I have the same behaviour by setting it to 1k, 3d or 9d: the bot plays indefinitely against itself._

Yes, because any "kyu-rank" bot can't pass or resign (see (3) above).

_Moreover, the play speed seems exactly the same as when set 30k._

Yes, because only the size of the subset is changed (see (1) above).

_I only get a difference when removing the kyu-rank: it is far slower and seems to have different gameplay, even when adding time settings._

Yes, because now the normal KataGo bot plays. Contrary to the "kyu-rank" mechanism (which only looks at the current position) it analyzes continuations until its thinking time per move runs out.

**Comment by illydone** [comment]
Seems clear, thanks.

For a beginner, this "ugly side of the coin" is an issue as he precisely needs help to find when the game should end and to count (among others) so setting kyu-rank isn't the best way to tune the AI IMHO. I'll check deeplier the way katago/leelazero are working, and will try to find the best network that have a not too high rank to play.

Thanks again.
