### ISSUE TITLE
Can not add branches in go4go's SGFs normally!

### ISSUE THREAD

**Issue by HackYardo** [aki65/aki65.github.io#57]
The "__go4go_branches.sgf.txt" below is too big and BadukAI is too slow...
[__baduk_branches.sgf.txt](https://github.com/aki65/aki65.github.io/files/8114597/__baduk_branch.sgf.txt)
[__baduk.sgf.txt](https://github.com/aki65/aki65.github.io/files/8114600/__baduk.sgf.txt)
[__go4go.sgf.txt](https://github.com/aki65/aki65.github.io/files/8114601/__go4go.sgf.txt)
[__go4go_branches.sgf.txt](https://github.com/aki65/aki65.github.io/files/8114656/__go4go_branches.sgf.txt)

**Comment by HackYardo** [comment]
I make four files to compare them, but my phone is too slow to open the fourth file. So I upload them.

**Comment by aki65** [comment]
I can load them all, but the fourth one is really huge and consists mostly of meaningless "\" characters. How did you produce it ?

**Comment by HackYardo** [comment]
> How produce the fourth file?

Just add a branch... And it seems that more branches, more bigger file size.

**Comment by HackYardo** [comment]
> How produce the fourth file?

Just add a branch... And it seems that more branches, more bigger file size.

**Comment by HackYardo** [comment]
You can try to add a branch in the original go4go sgf file here: 
[__go4go_20220121_Ichiriki-Ryo_Iyama-Yuta.sgf.txt](https://github.com/aki65/aki65.github.io/files/8121093/__go4go_20220121_Ichiriki-Ryo_Iyama-Yuta.sgf.txt)

**Comment by aki65** [comment]
The cause of the problem is that the go4go sgf file doesn't state its character encoding. Of course, BadukAI should handle this better (and I will include precautions for that in the next release), but for the time being you can avoid the problem by adding the encoding tag in the sgf file with a text editor. Add a line
CA[UTF-8]
for example between first and second line of the original file and the problem will disappear.

**Comment by HackYardo** [comment]
It solved, so I close the issue.
