### ISSUE TITLE
optimized don't support MTK?

### ISSUE THREAD

**Issue by ivysrono** [aki65/aki65.github.io#58]
I'm using [Xiaomi Poco X3 GT](https://www.gsmarena.com/xiaomi_poco_x3_gt-10949.php) with MediaTek MT6891Z Dimensity 1100 5G (6 nm).

ROM: https://developer.android.google.cn/topic/generic-system-image/releases aosp_arm64-exp-S2B3.220205.007.A1-8133516-58a8796c

1.13.2 optimized 40b : 10v/s
1.13.0 build in 20b     : 20v/s

**Comment by aki65** [comment]
It's the other way round: 
MTK doesn't support all NNAPI operations on the neural processing unit (NPU), some run only on CPU. As this is much slower, BadukAI is also much slower.

Unfortunately I can't do anything about this from BadukAI's side.

**Comment by ivysrono** [comment]
so we need snapdragon 8xx？6xx？

**Comment by aki65** [comment]
From reports and my own experience I know that NPU acceleration is working on
888
865
855
778G
768G
636

Generally speaking, BadukAI tries two ways to access the NPU
a) by DSP nnlib: This interface is offered by all older Snapdragon devices (but is blocked by some manufacturers since late 2020)
b) by NNAPI: This interface is working efficiently on newer Snapdragon devices (on older ones it's either non-existent or very slow)

So (a) _or_ (b) should work on almost all Snapdragon devices (with the possible exception of older chipsets that got a recent system update).

It's really disappointing that NPU acceleration doesn't work on Dimensity 1100, considering the hype Mediatek makes around their AI capabilities. If you can share the android log (while starting BadukAI) I can check if there are any helpful messages to track the problem down.

**Comment by aki65** [comment]
Yes, probably the new ROM blocks it. The report about 636 working came from a device which still had the original OS.

**Comment by ivysrono** [comment]
[baduk_ai.txt](https://github.com/aki65/aki65.github.io/files/8168472/baduk_ai.txt)

**Comment by aki65** [comment]
Thank you very much for the log. I made some changes which might fix the problem and published a test version here: https://github.com/aki65/aki65.github.io/releases/tag/v1.13.3
Please check if it works better than before and share the log again.

**Comment by ivysrono** [comment]
Worse for MTK 1100 ~30s

| network | 1.13.0 | 1.13.3 |
| - | - | - |
| 10B | 100v/s | 86.7v/s |
| 20B | 20v/s | 13.3v/s |
| 40B（1.13.2）| 10v/s |
| log | [1.13.0.txt](https://github.com/aki65/aki65.github.io/files/8168472/baduk_ai.txt) | just wait |

**Comment by aki65** [comment]
Thank you very much for your detailed report. Unfortunately some important diagnostic logging is at system level and therefore does not include "net.kir.baduk_ai". Could you please share the complete log ? And could you also run LeelaZero once while logging ? LZ's network is much simpler than KataGo's, so if it behaves differently that could give some clues ...

**Comment by ivysrono** [comment]
Updated.

**Comment by aki65** [comment]
Thanks for the full log. At least it's now clear what happened:

In 1.13.0 BadukAI had a whitelist of NNAPI accelerator names to use. The current Mediatek accelerators were not included in this list. because Mediatek has changed their names recently (which I was not aware of). So BadukAI didn't even try to use NNAPI but ran the networks on CPU (with the tensorflow lite implementation).

I already suspected that, so in 1.13.3 I deleted the whitelist check, so BadukAI uses the first NNAPI accelerator that it can find (in this case mtk-dsp). But this one can't handle the KataGo and LeelaZero network, so it again falls back on CPU (with the NNAPI implementation, which is even slower than the tensorflow lite implementation).

So what is left to try ?
1) I made two new apk-Files (https://github.com/aki65/aki65.github.io/releases/tag/v1.13.4) where BadukAI doesn't use the first accelerator it can find, but the other two ones that Mediatek offers: mtk-mdla and mtk-neuron. So please install baduk_ai__arm64-v8a-rel-1.14-mdla.apk and check the 20b (or 40b) KataGo network speed, then do the same with baduk_ai__arm64-v8a-rel-1.14-neuron.apk (no logs needed). To be honest, I don't have much hope here, but it's done quickly, so it can't hurt to try.

2) Mediatek offers an additional proprietary interface to the NPU. BadukAI doesn't use this, but you can check if that interface yields better speed by the following experiment:
- install the app "AI Benchmark" (from google play store or https://polybox.ethz.ch/index.php/s/80Jv0u3TP0Wd7o4/download)
- Start it and tap "Pro Mode" in the bottom right
- Tap "custom model" in the bottom row
- Tap "Select model" in the top right and choose the tflite-File of latest 40b network from 1.13.2
- Select "MediaTek Neuron" as acceleration
- Tap "Run" at the bottom
- It will show the mean time for one evaluation as "Avg Latency". If this one is significantly lower than 100ms, it's an improvement. In that case I will try to implement this method in BadukAI (if I can get access to a Mediatek device)

**Comment by ivysrono** [comment]
1.14 (both mdla and neuron) much faster than 1.13.0. I have updated the table.

While I click `custom model`, `AI Benchmark` 5.0.1 back to home without file select. Is there any other test app?

**Comment by aki65** [comment]
The error message in AI benchmark means that the MediaTek Neuron delegate can't handle the KataGo network (just as mtk-dsp in BaukAI 1.13.3). But that doesn't matter as now we have found two methods (mtk-mdla and mtk-neuron) that fully use the NPU to accelerate the network (the speeds you posted are just what I would expect according to general NPU performance benchmarks on Dimensity 1100). So I will add these accelerators in the next release. Until then you can use version 1.13.4, it's fully functional, it just has not gone through all the tests I make before releasing.

I will add your speeds to BadukAI's homepage for the next release, thanks again for all the testing.

In order to squeeze out the last bit of performance, you could try the following:
Tap "Edit config" in BadukAI's settings, set numSearchThreads=2 and tick "parallelEvaluation". On some devices this improves performance, on others not (depends on the structure of the NPU).

**Comment by ivysrono** [comment]
BTW, which FP16 score from https://ai-benchmark.com/ranking.html is the most important?

FP16  NNAPI 1.1
FP16  NNAPI 1.3
FP16  Accuracy
FP16  Parallel
FP16  NLP
FP16  Memory

**Comment by aki65** [comment]
INT8 NNAPI 1.1 is most important (You had to specify FP16 when running the KG model in the app, but only the external interface is FP16. The input is immediately quantized and all calculations are INT8).

BTW, did you try that "parallelEvaluation" switch I mentioned in the last post ? Did it change anything ?

**Comment by ivysrono** [comment]
> BTW, did you try that "parallelEvaluation" switch I mentioned in the last post ? Did it change anything ?

KG 20B speed is 1.5+ times faster than before, however, 10B and 40B may slower?

> the speeds you posted are just what I would expect according to general NPU performance benchmarks on Dimensity 1100

How expectations are calculated？

**Comment by aki65** [comment]
> however, 10B and 40B may slower?

10b is original KG network, not optimized, so is run on CPU. Therefore it doesn't profit from "parallelEvaluation", but suffers from changing 8 threads to 2 threads, since it can now utilize only 2 cpu cores instead of 8, so is much slower.

"parallelEvaluation" means that the SW is trying to run two network evaluations simultaneously on NPU. If the NPU is not fully occupied by one network, this gains some speed. But if the NPU is already completely busy with one network, these two evaluations may hinder each other. Therefore it's plausible that you get a speed gain for the smaller network but a loss for the bigger one, I had the same effect on my Snapdragon 855+.

> How expectations are calculated？

I look at the test in "AI benchmark" that is most similar to KataGo's network in terms of operations used. That is "DPED-ResNet" in version 4 (be careful, they changed the test in version 5, so don't look at the numbers of version 5). Then I use one of my own phones as reference point: Mi 11 has 3.1 ms in this test (for int8) and runs the 40b network at 80 v/s (without "parallelEvaluation"). Then I extrapolate linearly : Dimensity 1100 has 8.5 ms in this test, which translates to 29 v/s.
This is just a rough estimation: The test is only similar to KG's network, not identical. Linear extrapolation isn't really correct, since there is some fixed cost like data transfer and so on. But it's much better than nothing.

**Comment by ivysrono** [comment]
> DPED-ResNet

Where? https://ai-benchmark.com/ranking_processors_detailed.html has `DPED-ResNet` but no `Dimensity 1100` and the fastest `DPED-ResNet NN-INT8` is `13ms` from `Snapdragon 8 Gen 1`.

**Comment by aki65** [comment]
> That is "DPED-ResNet" in version 4 (be careful, they changed the test in version 5, so don't look at the numbers of version 5)

Your link shows the results of version 5. For version 4 go to

https://ai-benchmark.com/ranking_detailed_4_0_3.html   (by phone)
or
https://ai-benchmark.com/ranking_processors_detailed_4_0_3.html  (by processor)

**Comment by ivysrono** [comment]
> https://ai-benchmark.com/ranking_detailed_4_0_3.html (by phone) or https://ai-benchmark.com/ranking_processors_detailed_4_0_3.html (by processor)

Thanks. I have merged them to one excel by PowerQuery: [DPED-ResNet_NN-INT8(ms).xlsx](https://github.com/aki65/aki65.github.io/files/8238934/DPED-ResNet_NN-INT8.ms.xlsx)

BTW, 

> 10b is original KG network, not optimized

Why not?

**Comment by aki65** [comment]
Because

1. 10b is small, so already quite fast when running on CPU.
2. The optimized networks work only on 19x19 board (quantization can only be done effectively for a fixed board size), so for other board sizes an original KataGo network is needed. Therefore the app must include one.

**Comment by ivysrono** [comment]
https://github.com/aki65/aki65.github.io/pull/59
