### ISSUE TITLE
kyu-rank bot - I can't make a pass

### ISSUE THREAD

**Issue by nambung** [aki65/aki65.github.io#71]
when playing with kyu-rank bot, I can't make a pass.
thank you for a wonderful program! for the big boards, a special big thank you! this is amazing!

**Comment by aki65** [comment]
That's intentional, I disabled the "pass" button when the kyu-rank bot is active, because:
a) You don't need the pass, because it's playing with chinese rules, so you can play in your own territory without losing points.
b) The kyu-rank bot doesn't handle the pass correctly, because it assumes that black and white always put stones in turn. So, for example, if you play black and the kyu-rank bot plays white and you pass, then the kyu-rank bot "thinks" that it is black's turn (because the last stone played was white). So it will look for a good move for black (say, for example, it finds M4). Then the app will place a white stone at M4 (because the app handles the pass correctly). This was already wrong in all previous versions of BadukAI, but nobody ever noticed (including myself), because often a good point for black is also a good point for white (as the proverb says: "The enemy's key point is my key point"). Nonetheless, this is wrong, so I disabled the pass as an easy fix.
