### ISSUE TITLE
拍照识别棋谱，转换成sgf的时候，白子有时不能识别。

### ISSUE THREAD

**Issue by 1067511899** [aki65/aki65.github.io#80]
![IMG_20230430_193954](https://user-images.githubusercontent.com/21253207/235351190-5ffecba1-b98b-4311-b9db-e629c16dc28d.jpg)

这是拍照的那本书。

![Screenshot_20230430_193944_com foxwq yhwq](https://user-images.githubusercontent.com/21253207/235351204-aa807262-a009-4a34-a887-f5606eec14af.jpg)
这是用野狐围棋的拍照功能，识别了所有的棋子。（btw：腾讯围棋的也能完整识别）

![Screenshot_20230430_193905_net kir baduk_ai](https://user-images.githubusercontent.com/21253207/235351236-ce5bf7fe-b7ef-4c86-957d-1e8d5181c44e.jpg)
这个是用本软件的，有白子没有识别。

对于电脑显示器上的棋局，本软件倒是能正确识别。
请问能否增强一下识别的准确率？谢谢。

**Comment by HackYardo** [comment]
Perhaps it is caused by the markers(1,2,3,▲...) on stones, I'm not sure whether it can be solved or not. Let's call the author @aki65 for help.

**Comment by aki65** [comment]
The photo showcases three known weaknesses of detection in BadukAI:
1) Stones with numbers (or markings) are not well recognized 
2) Sometimes a non-existing stone is "detected" on a 1-1 point
3) Distortion of the board (leading to curved grid lines) is not handled well

Unfortunately, these are not easy to improve:
(1) and (2) are caused by incomplete training of the neural network detecting the stones. But I took the network as it is from an open source project, and I don't have the resources to re-train it.
(3) is caused by the basic concept of the algorithm, which detects the board by searching for straight lines. So changing this would require a completely new approach.

Fortunately, all three weaknesses are pretty easy to avoid / correct:
1) These are usually at most a few stones, so they are easy to check (and correct if necessary)
2) There are only four 1-1 points, so also easy to check.
3) This can happen only when taking photos from a book, and even then it can be avoided by putting some weight on the edges of the page, so that it is rather plain.
