### ISSUE TITLE
Improvements possible?

### ISSUE THREAD

**Issue by bltoby** [aki65/aki65.github.io#92]
1. I have often noticed that the ranking of possible moves is not adjusted properly or refreshed In time. As in the picture, the ranking is disordered. It should be c3 o17 c6 c7 p5 ......
![IMG_20230714_004142](https://github.com/aki65/aki65.github.io/assets/129069899/34dd3230-e175-45cc-891d-e18ae1332d04)

2. the background process of BadukAi sometimes get killed so quickly, can be in a few seconds. I tried every possible settings of my cellphone, but still with no success. I don't know if my cellphone is the reason? But is it possible to add an option, to let us set BadukAi keep running even if it is switched to the background? By the way, when switched to background, pondering will be stopped automatically. This is a great feature and it's essential to preserve the battery.
3. I don't use board zooming for 95% of the time, but often get the board zoomed by accident and can't get it unzoomed somehow. Can this zooming feature be made configurable?

**Comment by bltoby** [comment]
Thank you for replying.

For point 3 i can't describe how to reproduce it. But I recorded a short clip. When it happened, it was just very annoying and I couldn't get out the situation.

**Comment by bltoby** [comment]
For point 1

I don't know if it's really a good move to play like katago's first choice, as It will cause such a big territory loss for somehow a little bit better winning chance.
The ranking of moves is still a little bit weird.
![Screenshot_2023-07-20-22-05-33-50_9e9f7cd7a40ae8feef57515010bc9fb8](https://github.com/aki65/aki65.github.io/assets/129069899/276b44b8-539d-4d51-9646-1f647f7fe9dd)

**Comment by aki65** [comment]
For (3): Thank you very much for the video, that helped tracking down the issue. I found two timing problems, that might cause this effect, and fixed them. So please try the latest test release https://github.com/aki65/aki65.github.io/releases/tag/v1.18.10 and check if the problem is gone now.

For (1): In your example the move with the best win rate is the first choice, so the ordering seems plausible to me. Your irritation is probably caused by your interpretation of the "score-lead" as a "current territorial count" (in that case L3 would indeed be hard to understand). But that's not true. The "score-lead" is an estimation of the average final result of the game. 

So for L3 (which is the most aggressive fighting move) we could expect (numbers simplified):
15%: winning by 5 (if the fight goes well and turns the game around)
85%: losing by 28 (if the fight turns out badly, white will lose heavily)
which roughly leads to -23 on average.

L6 on the other hand (which is "safer") might yield:
5%: winning by 5 (much less chance of turning the game around)
95%: losing by 8 (because it "cuts down the losses")
which roughly leads to -7 on average.

But in go the margin of winning or losing doesn't matter, so L3 should be chosen (as the proverb says: "If you are behind, make the game complicated").

All this is just my intuitive understanding. If you want precise information about this, you should ask in the katago forum.

**Comment by aki65** [comment]
I made the fixes for (3) a little more robust in https://github.com/aki65/aki65.github.io/releases/tag/v1.18.11 , so please use that one instead of 1.18.10
